name: interval
description: A customizable interval timer app that allows users to set a main duration, work intervals, and rest intervals. Perfect for activities like workouts, study sessions, or any task requiring structured time management.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^9.2.0
  dartz: ^0.10.1
  device_preview: ^1.3.1
  duration_picker_dialog_box:
    git:
      url: https://github.com/NonymousMorlock/duration_picker_dialog_box.git
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_platform_alert: ^0.8.0
  gap: ^3.0.1
  get_it: ^9.2.0
  go_router: ^17.1.0
  http: ^1.6.0
  lottie: ^3.3.2
  path: ^1.9.1
  provider: ^6.1.5
  rive: ^0.14.3
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0
  wakelock_plus: ^1.4.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#F6F6F6"
    theme_color: "#0D47A1"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/rive/
    - assets/lottie/
